services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: DnDB
    volumes:
      - mysql_data:/var/lib/mysql
      - ./DnDB.sql:/docker-entrypoint-initdb.d/DnDB.sql

volumes:
  mysql_data: