services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: DnDB
    volumes:
      - ./data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/DnDB.sqlS